name: Generate Org Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  org-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: org-metrics.svg
          user: ""
          repo: ${{ github.repository }}
          base: header # 只保留头部
          plugin_introduction: yes
          plugin_introduction_title: "Our Organization Stats"
          config_debug: yes # 启用调试日志
        env:
          ORGANIZATION: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update organization metrics"
          git push
